.travis.yml, README.md
Issue: #1
Signed-off-by: Simon Rips <simon.rips@tngtech.com>
=> Add initial travis ci config

README.md, build.gradle, mock-junit/src/main/java/com/tngtech/keycloakmock/junit/KeycloakMock.java, mock-junit5/src/main/java/com/tngtech/keycloakmock/junit5/KeycloakMock.java, mock/src/main/java/com/tngtech/keycloakmock/api/TokenConfig.java
=> use release version plugin

README.md
=> fix travis URL

build.gradle, mock-junit/build.gradle, mock-junit5/build.gradle, mock/build.gradle, standalone/build.gradle
=> prepare POM generation for maven upload

build.gradle, standalone/build.gradle, standalone/src/main/resources/README.md
=> prepare POM generation for maven upload part 2 (#7)

build.gradle
=> prepare POM generation for maven upload part 3 (#7)

README.md
=> update README with maven coordinates

.github/workflows/build.yml, .travis.yml, README.md, build.gradle, example-backend/build.gradle, example-frontend-react/build.gradle, example-frontend-react/package.json, example-frontend-react/yarn.lock, gradle/wrapper/gradle-wrapper.properties, mock-junit/build.gradle, mock/src/main/java/com/tngtech/keycloakmock/api/KeycloakVerificationMock.java, standalone/build.gradle, standalone/src/main/java/com/tngtech/keycloakmock/standalone/Server.java, standalone/src/main/resources/iframe.ftl
and add support for Keycloak 8.0.1
=> update dependencies (#14)

build.gradle, example-backend/build.gradle, example-backend/src/main/java/com/tngtech/keycloakmock/examplebackend/ExampleBackendApplication.java, example-backend/src/main/java/com/tngtech/keycloakmock/examplebackend/rest/HelloController.java, example-backend/src/test/java/com/tngtech/keycloakmock/examplebackend/AuthenticationTest.java, example-frontend-react/build.gradle, example-frontend-react/package.json, example-frontend-react/yarn.lock, gradle/wrapper/gradle-wrapper.properties
=> return username in example app

example-backend/src/main/resources/application.yaml, example-frontend-react/README.md, example-frontend-react/public/keycloak.json, example-frontend-react/realm.json, standalone/build.gradle
=> provide keycloak config for local testing

example-frontend-react/src/App.js, example-frontend-react/src/components/Hello.jsx, example-frontend-react/src/index.js, standalone/src/main/java/com/tngtech/keycloakmock/standalone/Server.java
=> support logout in standalone server

standalone/src/main/java/com/tngtech/keycloakmock/standalone/Main.java
The server should only be stopped if something went wrong while starting it.
=> fix standalone

NOTICE, build.gradle, standalone/build.gradle, standalone/src/main/java/com/tngtech/keycloakmock/standalone/Main.java
- update notice file
- add version information to standalone
=> prepare release

.github/workflows/build.yml, mock/src/main/java/com/tngtech/keycloakmock/api/KeycloakVerificationMock.java, mock/src/main/java/com/tngtech/keycloakmock/api/MockServerException.java, mock/src/main/java/com/tngtech/keycloakmock/api/TokenConfig.java, mock/src/main/java/com/tngtech/keycloakmock/api/TokenGenerator.java, standalone/src/main/java/com/tngtech/keycloakmock/standalone/Server.java
=> fix interruption problem

README.md
=> update README.md after release

README.md
=> adapt README.md after release

NOTICE
=> update notice file

NOTICE, build.gradle
=> update notice and developers list

README.md
=> update release version in readme

README.md
update README to avoid deprecated method : withRealm is replaced by withDefaultRealm
=> update README to avoid deprecated method

mock/src/main/java/com/tngtech/keycloakmock/impl/handler/TokenRoute.java
Resolves #95 
Signed-off-by: wyfrel <wyfrel@gmail.com>
=>  add token_type attribute in access token responses Issue: #95

README.md, build.gradle, example-frontend-react/README.md, example-frontend-react/package.json, example-frontend-react/yarn.lock, example-integration-docker/realm.json, mock/build.gradle
=> document existing Keycloak configuration

.github/workflows/build.yml, CONTRIBUTING.md, build.gradle, example-backend/build.gradle, example-frontend-react/build.gradle, gradle/wrapper/gradle-wrapper.properties, mock/build.gradle, standalone/build.gradle
Changes:
* update dependencies
* update contribution guidelines
* add test output to github actions
Sorry for the branch name, I got confused and did not delete the branch last time (even though it had been merged already).
=> various fixes

.github/workflows/build.yml, build.gradle
=> use new sonar task

.github/workflows/build.yml, mock/src/main/java/com/tngtech/keycloakmock/api/MockServerException.java, mock/src/main/java/com/tngtech/keycloakmock/api/ServerConfig.java, mock/src/main/java/com/tngtech/keycloakmock/api/TokenConfig.java
=> fix Javadoc

mock/src/main/java/com/tngtech/keycloakmock/impl/TokenGenerator.java, mock/src/test/java/com/tngtech/keycloakmock/impl/TokenGeneratorTest.java
=> fill more JWT header fields
